(()=>{"use strict";var e={d:(a,t)=>{for(var r in t)e.o(t,r)&&!e.o(a,r)&&Object.defineProperty(a,r,{enumerable:!0,get:t[r]})},o:(e,a)=>Object.prototype.hasOwnProperty.call(e,a),r:e=>{"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})}},a={};e.r(a),e.d(a,{configuration:()=>b});const t=("undefined"!=typeof window?window:global).MathJax._.components.global,r=(t.GLOBAL,t.isObject,t.combineConfig,t.combineDefaults,t.combineWithMathJax),o=(t.MathJax,MathJax._.input.tex.NodeUtil.default),n=MathJax._.input.tex.Configuration,c=n.Configuration,m=(n.ConfigurationHandler,n.ParserConfiguration,MathJax._.input.tex.TokenMap),s=(m.parseResult,m.AbstractTokenMap,m.RegExpMap,m.AbstractParseMap,m.CharacterMap,m.DelimiterMap),i=(m.MacroMap,m.CommandMap),l=(m.EnvironmentMap,MathJax._.input.tex.TexConstants.TexConstant),d=MathJax._.input.tex.ParseMethods.default,h=MathJax._.input.tex.base.BaseMethods,M=(h.splitAlignArray,h.default);
/*!
 *  Copyright (c) 2020 American Mathematical Society
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
let u={accentset:function(e,a){const t=e.ParseArg(a),r=e.ParseArg(a);t.isKind("mo")&&o.setAttribute(t,"accent",!0),o.setAttribute(t,"mathsize","small"),e.stack.env.font&&o.setAttribute(t,"mathvariant",e.stack.env.font);const n=e.create("node","mpadded",[t],{height:0}),c=e.create("node","mover",[r,n]),m=e.create("node","TeXAtom",[c]);e.Push(m)},smallcaps:function(e,a){let t=e.GetArgument(a);const r={mathsize:"1em",mathvariant:"normal"};for(let a of t)a.toLowerCase()===a?r.mathsize="0.8em":r.mathsize="1em",e.Push(e.create("token","mi",r,a.toUpperCase()))},bevelledFraction:function(e,a){const t=e.ParseArg(a),r=e.ParseArg(a),o=e.create("node","mfrac",[t,r],{bevelled:!0});e.Push(o)}};u.Macro=M.Macro,u.Accent=M.Accent,u.SetFont=M.SetFont,new i("ams-macros-macros",{pmod:["Macro","\\mathchoice{\\mkern18mu}{\\mkern12mu}{\\mkern12mu}{\\mkern12mu}(\\operatorname{mod}\\mkern6mu #1)",1],bigsqcap:["Macro","\\mmlToken{mo}{\u2a05}"],lefteqn:["Macro","\\rlap{\\displaystyle{#1}}",1],sslash:["Macro","\u2afd"],square:["Macro","\u25fb"],Box:["Macro","\u25fb"],mathds:["Macro","\\mathbb{#1}",1],blacktriangle:["Macro","\u25b4"],coloneq:["Macro","\\mathrel{\u2254}"],adots:["Macro","\u22f0"],overarc:["Accent","2312",1],widecheck:["Accent","02C7",1],accentset:"accentset",intbar:["Macro","\\mmlToken{mo}{\u2a0d}"],bfit:["SetFont",l.Variant.BOLDITALIC],mathbfit:["Macro","{\\bfit #1}",1],mathsc:"smallcaps",mathbfcal:["Macro","\\boldsymbol{\\mathcal{#1}}",1],sfrac:"bevelledFraction",Sha:["Macro","\\mathrm{\u0428}"],Shcha:["Macro","\\mathrm{\u0429}"],De:["Macro","\\mathrm{\u0434}"],txt:["Macro","\\vcenter{\\makebox{#1}}",1]},u),new s("ams-macros-delimiters",d.delimiter,{"\\Vvert":"\u2980","\\llbracket":"\u27e6","\\rrbracket":"\u27e7","\\llangle":"\u2989","\\rrangle":"\u298a","\\lAngle":"\u27ea","\\rAngle":"\u27eb"});const b=c.create("ams-macros",{handler:{delimiter:["ams-macros-delimiters"],macro:["ams-macros-macros","ams-macros-delimiters"]}});MathJax.loader&&MathJax.loader.checkVersion("[ams]/ams-macros","4.0.0-beta.4","tex-extension"),r({_:{"ams-macros":a}})})();